Card like
WildCodeSchool-2024-02/JS-Paris-BrainWaves-P3-Gems pull request #31
Opened 2024-07-10 14:37 UTC by Curtisdak

2024-07-10 14:54 UTC, Coline1186 approved these changes

2024-07-10 15:07 UTC, Alexandre78R requested changes

2024-07-10 15:07 UTC, Alexandre78R commented on client/src/components/Card/Card.css
> +  margin-top: -5px;
No value negatif

2024-07-11 12:58 UTC, Alexandre78R approved these changes

2024-07-11 12:58 UTC, merged